doinstall: added more exit

diff --git a/doinstall b/doinstall
--- a/doinstall
+++ b/doinstall
@@ -12,82 +12,88 @@ unset LD_BIND_NOW
 unset LD_LIBRARY_PATH
 unset LD_PRELOAD
 
-logger -s -t installer '[1/5] Начало установки системы пакетов "Entware"...'
+logger -t installer '[1/5] Начало установки системы пакетов "Entware"...'
 
 # checking "opkg dns-override"
 if [ "$(ndmq -p "show running-config" -P message | grep "opkg dns-override")" = "opkg dns-override" ]; then
-	logger -s -t installer 'Info: Have you activated "opkg dns-override" in CLI/web?'
-	logger -s -t installer 'Critical error: Продолжение установки невозможно!'
-	logger -s -t installer 'Выход из установки.'
+	logger -t installer 'Info: Активирована настройка "opkg dns-override"...'
+	logger -t installer 'Critical error: Продолжение установки невозможно!'
+	logger -t installer 'Выход из установки.'
 	exit 1
 fi
 
 # checking "opkg timezone"
 if [ "$(ndmq -p "show running-config" -P message | grep "opkg timezone" | cut -d' ' -f1,2)" = "opkg timezone" ]
   then
-	logger -s -t installer 'Info: Have you activated "opkg timezone" in CLI/web?'
-	ndmq -p "opkg timezone $timezone"
+	logger -t installer 'Info: Активирована настройка "opkg timezone"...'
+	logger -t installer 'Critical error: Продолжение установки невозможно!'
+	logger -t installer 'Выход из установки.'
+	exit 1
+#	ndmq -p "opkg timezone $timezone"
 fi
 
 # checking "opkg chroot"
 if [ "$(ndmq -p "show running-config" -P message | grep "opkg chroot")" = "opkg chroot" ]; then
-	logger -s -t installer 'Info: Have you activated "opkg chroot" in CLI/web?'
-	for files in group passwd profile shell; do rm -f /opt/etc/$files; done
-	for files in hosts resolv.conf; do cp /tmp/$files /opt/etc/; done
+	logger -t installer 'Info: Активирована настройка "opkg chroot"...'
+	logger -t installer 'Critical error: Продолжение установки невозможно!'
+	logger -t installer 'Выход из установки.'
+	exit 1
+#	for files in group passwd profile shell; do rm -f /opt/etc/$files; done
+#	for files in hosts resolv.conf; do cp /tmp/$files /opt/etc/; done
 # checking opt fs
-	check_fs_opt="$(mount | grep 'on / ' | cut -d' ' -f5)"
+#	check_fs_opt="$(mount | grep 'on / ' | cut -d' ' -f5)"
   else
 	check_fs_opt="$(mount | grep 'on /opt ' | cut -d' ' -f5)"
 fi
 
 case "$check_fs_opt" in
     ext*)
-	logger -s -t installer 'Info: Раздел пригоден для установки.'
+	logger -t installer 'Info: Раздел пригоден для установки.'
     ;;
     *ntfs*)
-	logger -s -t installer 'Info: Раздел NTFS! атрибуты "user:group" могут не поддерживаться.'
-	logger -s -t installer 'При возникновении проблем, используйте накопитель с файловой системой ext2/ext3/ext4.'
+	logger -t installer 'Info: Раздел NTFS! Атрибуты "owner:group" могут не поддерживаться.'
+	logger -t installer 'При возникновении проблем, используйте накопитель с файловой системой ext2/ext3/ext4.'
     ;;
     *hfs*)
-	logger -s -t installer 'Info: Раздел с HFS! (!не тестировалось!).'
-	logger -s -t installer 'При возникновении проблем, используйте накопитель с файловой системой ext2/ext3/ext4.'
+	logger -t installer 'Info: Раздел с HFS! (!не тестировалось!)'
+	logger -t installer 'При возникновении проблем, используйте накопитель с файловой системой ext2/ext3/ext4.'
     ;;
     ubifs)
-	logger -s -t installer 'Info: Раздел с UBIFS! (!не тестировалось!).'
-	logger -s -t installer 'При возникновении проблем, используйте накопитель с файловой системой ext2/ext3/ext4.'
+	logger -t installer 'Info: Раздел с UBIFS! (!не тестировалось!)'
+	logger -t installer 'При возникновении проблем, используйте внешний накопитель с файловой системой ext2/ext3/ext4.'
     ;;
     *)
-        logger -s -t installer 'Critical error: Неизвестный тип ФС. Используйте накопитель с файловой системой ext2/ext3/ext4. Отменяем...'
-	logger -s -t installer 'Выход из установки.'
+        logger -t installer 'Critical error: Неизвестный тип ФС. Используйте накопитель с файловой системой ext2/ext3/ext4. Отменяем...'
+	logger -t installer 'Выход из установки.'
 	exit 1
     ;;
 esac
 
 # checking network
-logger -s -t installer 'Info: "ping google.com"...'
+logger -t installer 'Info: "ping google.com"...'
 if ! ping -c 3 google.com >/dev/null 2>&1
   then
-	logger -s -t installer 'Critical error: Ресурс недоступен. Проверьте настройки сети.'
-	logger -s -t installer 'Выход из установки.'
+	logger -t installer 'Critical error: Ресурс недоступен. Проверьте настройки сети.'
+	logger -t installer 'Выход из установки.'
 	exit 1
   else
-	logger -s -t installer 'Info: "ping google.com" ..... OK'
+	logger -t installer 'Info: "ping google.com" ..... OK'
 	sleep 1
 fi
 
-logger -s -t installer 'Info: "ping bin.entware.net"...'
+logger -t installer 'Info: "ping bin.entware.net"...'
 if ! ping -c 3 bin.entware.net >/dev/null 2>&1
   then
-	logger -s -t installer 'Critical error: Ресурс недоступен. Повторите попытку позже.'
-	logger -s -t installer 'Выход из установки.'
+	logger -t installer 'Critical error: Ресурс недоступен. Повторите попытку позже.'
+	logger -t installer 'Выход из установки.'
 	exit 1
   else
-	logger -s -t installer 'Info: "ping bin.entware.net" ..... OK'
+	logger -t installer 'Info: "ping bin.entware.net" ..... OK'
 	sleep 1
 fi
 
 # Только для opkg. Остальные каталоги будут созданы пакетом opt-ndmsv2
-logger -s -t installer 'Info: Создание каталогов...'
+logger -t installer 'Info: Создание каталогов...'
 for folder in lib/opkg tmp var/lock; do
   if [ ! -d "/opt/$folder" ]; then
     mkdir -p /opt/$folder
@@ -95,25 +101,25 @@ for folder in lib/opkg tmp var/lock; do
 done
 
 # opkg update
-logger -s -t installer '[2/5] Загрузка и установка основных пакетов...'
+logger -t installer '[2/5] Загрузка и установка основных пакетов...'
 if ! opkg update >/dev/null 2>&1
   then
-	logger -s -t installer 'Critical error: Во время обновления списка пакетов произошла ошибка.'
-	logger -s -t installer 'Выход из установки.'
+	logger -t installer 'Critical error: Во время обновления списка пакетов произошла ошибка.'
+	logger -t installer 'Выход из установки.'
 	exit 1
 fi
 
 # install basic packages
 for ipk in libgcc libc libpthread librt entware-release findutils grep ldconfig locales ndmq opkg zoneinfo-asia zoneinfo-europe opt-ndmsv2 dropbear poorbox busybox
  do
-	logger -s -t installer "Info: Устанавливается пакет \"$ipk\"..."
+	logger -t installer "Info: Устанавливается пакет \"$ipk\"..."
   if ! opkg install $ipk >/dev/null 2>&1
     then
-	logger -s -t installer "Critical error: Во время установки пакета \"$ipk\" произошла ошибка."
-	logger -s -t installer 'Выход из установки.'
+	logger -t installer "Critical error: Во время установки пакета \"$ipk\" произошла ошибка."
+	logger -t installer 'Выход из установки.'
 	exit 1
     else
-	logger -s -t installer "Info: Пакет \"$ipk\" установлен."
+	logger -t installer "Info: Пакет \"$ipk\" установлен."
 	sleep 2
   fi
     if [ "$ipk" = "libc" ]; then
@@ -121,7 +127,7 @@ for ipk in libgcc libc libpthread librt entware-release findutils grep ldconfig 
     fi
 done
 
-logger -s -t installer 'Info: Установка пакетов прошла успешно!'
+logger -t installer 'Info: Установка пакетов прошла успешно!'
 
 ldconfig >/dev/null 2>&1
 
@@ -132,23 +138,23 @@ chmod 777 /opt/tmp
 dots-n.sh &
 
 # keygen
-logger -s -t installer '[3/5] Генерация SSH-ключей...'
+logger -t installer '[3/5] Генерация SSH-ключей...'
 
 for key in rsa ecdsa ed25519; do
   rm /opt/etc/dropbear/dropbear_${key}_host_key
-	logger -s -t installer "Info: Генерируется ключ \"$key\"..."
+	logger -t installer "Info: Генерируется ключ \"$key\"..."
   if ! dropbearkey -t $key -f /opt/etc/dropbear/dropbear_${key}_host_key >/dev/null 2>&1
     then
-	logger -s -t installer "Critical error: Во время генерации ключа \"$key\" произошла ошибка."
-	logger -s -t installer 'Выход из установки.'
+	logger -t installer "Critical error: Во время генерации ключа \"$key\" произошла ошибка."
+	logger -t installer 'Выход из установки.'
 	exit 1
     else
-	logger -s -t installer "Info: Ключ \"$key\" создан."
+	logger -t installer "Info: Ключ \"$key\" создан."
 	sleep 1
   fi
 done
 
-logger -s -t installer '[4/5] Настройка сценария запуска, установка часового пояса и запуск "dropbear"...'
+logger -t installer '[4/5] Настройка сценария запуска, установка часового пояса и запуск "dropbear"...'
 
 # TZ
 timezone="$(ndmq -p "show clock date" -P tz/locality)"
@@ -165,12 +171,12 @@ ndmq -p "opkg initrc /opt/etc/init.d/rc.unslung"
 ndmq -p "system configuration save"
 
 if grep -q "222" /opt/etc/config/dropbear.conf; then
-	logger -s -t installer 'Можно открыть SSH-сессию для соединения с устройством (логин - root, пароль - keenetic, порт - 222).'
+	logger -t installer 'Можно открыть SSH-сессию для соединения с устройством (логин - root, пароль - keenetic, порт - 222).'
   else
-	logger -s -t installer 'Можно открыть SSH-сессию для соединения с устройством (логин - root, пароль - keenetic).'
+	logger -t installer 'Можно открыть SSH-сессию для соединения с устройством (логин - root, пароль - keenetic).'
 fi
 
-logger -s -t installer '[5/5] Установка системы пакетов "Entware" завершена! Не забудьте сменить пароль и номер порта!'
+logger -t installer '[5/5] Установка системы пакетов "Entware" завершена! Не забудьте сменить пароль и номер порта!'
 
 rm /opt/bin/dots.sh
 rm /opt/bin/dots-n.sh
