doinstall: refresh

diff --git a/doinstall b/doinstall
--- a/doinstall
+++ b/doinstall
@@ -36,7 +36,7 @@ case "$check_fs_opt" in
 	logger -t installer 'Info: Раздел пригоден для установки.'
     ;;
     *ntfs*)
-	logger -t installer 'Info: Раздел NTFS! атрибуты "пользователь:группа" могут не поддерживаться.'
+	logger -t installer 'Info: Раздел NTFS! атрибуты "user:group" могут не поддерживаться.'
 	logger -t installer 'При возникновении проблем, используйте накопитель с файловой системой ext2/ext3/ext4.'
     ;;
     *hfs*)
@@ -53,17 +53,28 @@ esac
 # checking network
 if ! ping -c 5 google.com > /dev/null 2>&1
   then
-	logger -t installer 'Critical error: Проверьте настройки сети.'
+	logger -t installer 'Critical error: Ресурс недоступен. Проверьте настройки сети.'
 	logger -t installer 'Выход из установки.'
 	exit 1
   else
 	logger -t installer 'Info: "ping google.com" ..... OK'
+	sleep 1
 fi
 
-logger -t installer '[1/5] Начало установки системы "Entware"...'
+if ! ping -c 5 bin.entware.net > /dev/null 2>&1
+  then
+	logger -t installer 'Critical error: Ресурс недоступен. Повторите попытку позже.'
+	logger -t installer 'Выход из установки.'
+	exit 1
+  else
+	logger -t installer 'Info: "ping bin.entware.net" ..... OK'
+	sleep 1
+fi
+
+logger -t installer '[1/5] Начало установки системы пакетов "Entware"...'
 
 # This is for opkg only. The other folders will be created from opt-ndmsv2 package
-# Только для opkg. Остальные каталоги будут созданы пакетом opt-ndmsv1/2
+# Только для opkg. Остальные каталоги будут созданы пакетом opt-ndmsv2
 logger -t installer 'Info: Создание каталогов...'
 
 for folder in lib/opkg tmp var/lock; do
@@ -73,26 +84,26 @@ done
 logger -t installer '[2/5] Загрузка и установка основных пакетов...'
 if ! opkg update > /dev/null 2>&1
   then
-	logger -t installer 'Critical error: Во время обновления списка пакетов возникла ошибка.'
+	logger -t installer 'Critical error: Во время обновления списка пакетов произошла ошибка.'
 	logger -t installer 'Выход из установки.'
 	exit 1
 fi
 
 # install base packages
-for ipk in libc opt-ndmsv2 grep poorbox dropbear busybox; do
+for ipk in libgcc libc libpthread librt entware-release findutils grep ldconfig locales ndmq opkg zoneinfo-asia zoneinfo-europe opt-ndmsv2 dropbear poorbox busybox; do
 	logger -t installer "Info: Устанавливается пакет \"$ipk\"..."
   if ! opkg install $ipk > /dev/null 2>&1
     then
-	logger -t installer "Critical error: Во время установки пакета \"$ipk\" возникла ошибка."
+	logger -t installer "Critical error: Во время установки пакета \"$ipk\" произошла ошибка."
 	logger -t installer 'Выход из установки.'
 	exit 1
     else
 	logger -t installer "Info: Пакет \"$ipk\" установлен."
-	sleep 2
-      if [ "$ipk" = "libc" ]; then
-	dots.sh &
-      fi
+	sleep 1
   fi
+    if [ "$ipk" = "libc" ]; then
+	dots.sh &
+    fi
 done
 
 logger -t installer 'Info: Установка пакетов прошла успешно!'
@@ -112,16 +123,16 @@ for key in rsa ecdsa; do
 	logger -t installer "Info: Генерируется ключ \"$key\"..."
   if ! dropbearkey -t $key -f /opt/etc/dropbear/dropbear_${key}_host_key > /dev/null 2>&1
     then
-	logger -t installer "Critical error: Во время генерации ключа \"$key\" возникла ошибка."
+	logger -t installer "Critical error: Во время генерации ключа \"$key\" произошла ошибка."
 	logger -t installer 'Выход из установки.'
 	exit 1
     else
 	logger -t installer "Info: Ключ \"$key\" создан."
-	sleep 2
+	sleep 1
   fi
 done
 
-logger -t installer '[4/5] Настройка сценария запуска, установка часового пояса и запуск dropbear...'
+logger -t installer '[4/5] Настройка сценария запуска, установка часового пояса и запуск "dropbear"...'
 
 # TZ
 timezone="$(ndmq -p "show clock date" -P tz/locality)"
@@ -143,6 +154,6 @@ if grep -q "222" /opt/etc/config/dropbear.conf; then
 	logger -t installer 'Можно открыть SSH-сессию для соединения с устройством (ssh root:keenetic@my.keenetic.net).'
 fi
 
-logger -t installer '[5/5] Установка "Entware" завершена! Не забудьте сменить пароль и номер порта!'
+logger -t installer '[5/5] Установка системы пакетов "Entware" завершена! Не забудьте сменить пароль и номер порта!'
 
 rm "$0"
