EN_doinstall: switch from logger to echo

diff --git a/EN_doinstall b/EN_doinstall
--- a/EN_doinstall
+++ b/EN_doinstall
@@ -11,19 +11,19 @@ unset LD_BIND_NOW
 unset LD_LIBRARY_PATH
 unset LD_PRELOAD
 
-logger -t installer '[1/5] Starting "Entware" deployment...'
+echo '[1/5] Starting "Entware" deployment...'
 
 # checking opkg timezone
 if [ "$(ndmq -p "show running-config" -P message | grep "opkg timezone" | cut -d' ' -f1,2)" = "opkg timezone" ]
   then
-	logger -t installer 'Info: Have you activated "opkg timezone" in CLI/web?'
+	echo 'Info: Have you activated "opkg timezone" in CLI/web?'
 	ndmq -p "opkg timezone $timezone"
 fi
 
 # checking opkg chroot
 if [ "$(ndmq -p "show running-config" -P message | grep "opkg chroot")" = "opkg chroot" ]; then
-	logger -t installer 'Info: Have you activated "opkg chroot" in CLI/web?'
-#	logger -t installer 'Wow, OK!'
+	echo 'Info: Have you activated "opkg chroot" in CLI/web?'
+#	echo 'Wow, OK!'
 	for files in group passwd profile shell; do rm -f /opt/etc/$files; done
 	for files in hosts resolv.conf; do cp /tmp/$files /opt/etc/; done
 # checking opt fs
@@ -34,43 +34,43 @@ fi
 
 case "$check_fs_opt" in
     ext*)
-	logger -t installer 'Partition is OK.'
+	echo 'Partition is OK.'
     ;;
     *ntfs*)
-	logger -t installer 'NTFS partition! owner:group attributes may not be supported.'
-	logger -t installer 'Please, use ext2/ext3/ext4 if something goes wrong.'
+	echo 'NTFS partition! owner:group attributes may not be supported.'
+	echo 'Please, use ext2/ext3/ext4 if something goes wrong.'
     ;;
     *hfs*)
-	logger -t installer 'HFS partition is not tested.'
-	logger -t installer 'Please, use ext2/ext3/ext4 if something goes wrong.'
+	echo 'HFS partition is not tested.'
+	echo 'Please, use ext2/ext3/ext4 if something goes wrong.'
     ;;
     *)
-        logger -t installer 'Please use ext2/ext3/ext4 formatted storage. Aborting...'
-	logger -t installer 'Exit.'
+        echo 'Please use ext2/ext3/ext4 formatted storage. Aborting...'
+	echo 'Exit.'
 	exit 1
     ;;
 esac
 
 # checking network
-logger -t installer 'Info: "ping google.com"...'
-if ! ping -c 3 google.com > /dev/null 2>&1
+echo 'Info: "ping google.com"...'
+if ! ping -c 3 google.com >/dev/null 2>&1
   then
-	logger -t installer 'Critical error: The resource is not available. Check your network settings.'
-	logger -t installer 'Exit.'
+	echo 'Critical error: The resource is not available. Check your network settings.'
+	echo 'Exit.'
 	exit 1
   else
-	logger -t installer 'Info: "ping google.com" ..... OK'
+	echo 'Info: "ping google.com" ..... OK'
 	sleep 1
 fi
 
-logger -t installer 'Info: "ping bin.entware.net"...'
-if ! ping -c 3 bin.entware.net > /dev/null 2>&1
+echo 'Info: "ping bin.entware.net"...'
+if ! ping -c 3 bin.entware.net >/dev/null 2>&1
   then
-	logger -t installer 'Critical error: The resource is not available. Please try again later.'
-	logger -t installer 'Exit.'
+	echo 'Critical error: The resource is not available. Please try again later.'
+	echo 'Exit.'
 	exit 1
   else
-	logger -t installer 'Info: "ping bin.entware.net" ..... OK'
+	echo 'Info: "ping bin.entware.net" ..... OK'
 	sleep 1
 fi
 
@@ -79,57 +79,58 @@ for folder in lib/opkg tmp var/lock; do
 	mkdir -p /opt/$folder
 done
 
-logger -t installer '[2/5] Basic packages installation...'
-if ! opkg update > /dev/null 2>&1
+echo '[2/5] Basic packages installation...'
+if ! opkg update >/dev/null 2>&1
   then
-	logger -t installer 'Critical error: An error occurred while updating the package list.'
-	logger -t installer 'Exit.'
+	echo 'Critical error: An error occurred while updating the package list.'
+	echo 'Exit.'
 	exit 1
 fi
 
 # install base packages
-for ipk in libgcc libc libpthread librt entware-release findutils grep ldconfig locales ndmq opkg zoneinfo-asia zoneinfo-europe opt-ndmsv2 dropbear poorbox busybox; do
-	logger -t installer "Info: Installing \"$ipk\" package..."
-  if ! opkg install $ipk > /dev/null 2>&1
+for ipk in libgcc libc libpthread librt entware-release findutils grep ldconfig locales ndmq opkg zoneinfo-asia zoneinfo-europe opt-ndmsv2 dropbear poorbox busybox
+ do
+	echo "Info: Installing \"$ipk\" package..."
+  if ! opkg install $ipk >/dev/null 2>&1
     then
-	logger -t installer "Critical error: An error occurred while installing the \"$ipk\" package."
-	logger -t installer 'Exit.'
+	echo "Critical error: An error occurred while installing the \"$ipk\" package."
+	echo 'Exit.'
 	exit 1
     else
-	logger -t installer "Info: The \"$ipk\" package has been installed."
-	sleep 1
+	echo "Info: The \"$ipk\" package has been installed."
+	sleep 2
   fi
     if [ "$ipk" = "libc" ]; then
 	dots.sh &
     fi
 done
 
-logger -t installer 'Info: All basic packages are installed...'
+echo 'Info: All basic packages were installed...'
 
 dots-n.sh &
-ldconfig > /dev/null 2>&1
+ldconfig >/dev/null 2>&1
 
 # Fix for multiuser environment
 chmod 777 /opt/tmp
 
 # keygen
-logger -t installer '[3/5] Generating SSH keys...'
+echo '[3/5] Generating SSH keys...'
 
 for key in rsa ecdsa; do
   rm /opt/etc/dropbear/dropbear_${key}_host_key
-	logger -t installer "Info: Generating \"$key\" key..."
-  if ! dropbearkey -t $key -f /opt/etc/dropbear/dropbear_${key}_host_key > /dev/null 2>&1
+	echo "Info: Generating \"$key\" key..."
+  if ! dropbearkey -t $key -f /opt/etc/dropbear/dropbear_${key}_host_key >/dev/null 2>&1
     then
-	logger -t installer "Critical error: An error occurred while generating \"$key\" key."
-	logger -t installer 'Exit.'
+	echo "Critical error: An error occurred while generating \"$key\" key."
+	echo 'Exit.'
 	exit 1
     else
-	logger -t installer "Info: \"$key\" key was created."
+	echo "Info: \"$key\" key was created."
 	sleep 1
   fi
 done
 
-logger -t installer '[4/5] Setting timezone, script initrc and starting "dropbear"...'
+echo '[4/5] Setting timezone, script initrc and starting "dropbear"...'
 
 # TZ
 timezone="$(ndmq -p "show clock date" -P tz/locality)"
@@ -146,11 +147,11 @@ ndmq -p "opkg initrc /opt/etc/init.d/rc.unslung"
 ndmq -p "system configuration save"
 
 if grep -q "222" /opt/etc/config/dropbear.conf; then
-	logger -t installer 'Log on at "root:keenetic@my.keenetic.net -p 222" to start new SSH session.'
+	echo 'Log on at "root:keenetic@my.keenetic.net -p 222" to start new SSH session.'
   else
-	logger -t installer 'Log on at "root:keenetic@my.keenetic.net" to start new SSH session.'
+	echo 'Log on at "root:keenetic@my.keenetic.net" to start new SSH session.'
 fi
 
-logger -t installer '[5/5] "Entware" installed!'
+echo '[5/5] "Entware" installed!'
 
 rm "$0"
